import type { Booking, Settings } from '../types';
import { formatRupiah, formatWeight, formatDateIndonesian, normalizePhone } from './utils';

/**
 * PRD Section 46: WhatsApp Booking Message
 * Generates structured prefilled message sent by Customer to Outlet upon booking creation.
 */
export function buildBookingWhatsAppMessage(booking: Booking, settings: Settings): string {
  const methodText = booking.serviceMode === 'PICKUP' ? 'Pickup' : 'Antar Sendiri (Self Drop-off)';
  
  let msg = `Halo Min, saya mau booking laundry di ${settings.laundryName}.\n\n`;
  msg += `Nama: ${booking.customerName}\n`;
  msg += `Metode: ${methodText}\n`;
  
  if (booking.serviceMode === 'PICKUP') {
    msg += `Jarak: ${booking.distanceKm ?? 0} km\n\n`;
    msg += `Alamat:\n${booking.pickupAddress || '-'}\n\n`;
    if (booking.pickupLandmark) {
      msg += `Patokan: ${booking.pickupLandmark}\n\n`;
    }
    if (booking.scheduledDate) {
      msg += `Jadwal: ${formatDateIndonesian(booking.scheduledDate)}\n`;
    }
    if (booking.pickupSlotName && booking.pickupSlotTime) {
      msg += `Slot: ${booking.pickupSlotName} (${booking.pickupSlotTime})\n`;
    }
  }

  msg += `\nLayanan: ${booking.serviceName}\n`;
  if (booking.estimatedQuantity) {
    msg += `Estimasi: ${booking.estimatedQuantity}\n`;
  }
  if (booking.notes) {
    msg += `Catatan: ${booking.notes}\n`;
  }
  
  msg += `\nBooking Reference:\n*${booking.bookingCode}*\n\n`;
  msg += `Mohon konfirmasinya ya Min. Terima kasih!`;

  return msg;
}

/**
 * PRD Section 45: WhatsApp Billing Message
 * Generated by Admin to send the final bill breakdown with actual weight to Customer.
 */
export function buildBillingWhatsAppMessage(booking: Booking, settings: Settings): string {
  const weight = formatWeight(booking.actualWeight);
  const subtotal = formatRupiah(booking.subtotal);
  const pickupFee = formatRupiah(booking.pickupFee);
  const total = formatRupiah(booking.total);

  let msg = `Halo Kak ${booking.customerName},\n\n`;
  msg += `Cucian Kakak dengan Kode *${booking.bookingCode}* sudah selesai kami timbang di outlet ${settings.laundryName}.\n\n`;
  msg += `Berat Aktual: *${weight}*\n\n`;
  msg += `Rincian Tagihan:\n`;
  msg += `• Laundry: ${weight} × ${formatRupiah(booking.unitPrice)} = ${subtotal}\n`;
  if (booking.pickupFee > 0) {
    msg += `• Biaya Pickup: ${pickupFee}\n`;
  }
  if (booking.discount > 0) {
    msg += `• Diskon: -${formatRupiah(booking.discount)}\n`;
  }
  msg += `*Total Tagihan: ${total}*\n\n`;
  
  msg += `Pembayaran dapat dilakukan melalui:\n`;
  if (settings.bankName && settings.bankAccountNumber) {
    msg += `• Transfer ${settings.bankName}: ${settings.bankAccountNumber} (a.n ${settings.bankAccountName || settings.laundryName})\n`;
  }
  if (settings.qrisImageUrl) {
    msg += `• QRIS (silakan minta QR ke kami)\n`;
  }
  if (settings.cashEnabled) {
    msg += `• Cash / Tunai saat serah terima cucian\n`;
  }

  msg += `\nFoto timbangan dapat kami lampirkan ya Kak.\nTerima kasih banyak!`;
  return msg;
}

/**
 * PRD Section 49: Status Notification Templates
 */
export function buildStatusWhatsAppMessage(
  booking: Booking,
  status: 'RECEIVED' | 'PROCESSING' | 'READY' | 'COMPLETED',
  settings: Settings
): string {
  switch (status) {
    case 'RECEIVED':
      return (
        `Halo Kak ${booking.customerName},\n\n` +
        `Cucian dengan Kode *${booking.bookingCode}* sudah kami terima dan timbang di ${settings.laundryName}.\n\n` +
        `Berat: ${formatWeight(booking.actualWeight)}\n` +
        `Total: ${formatRupiah(booking.total)}\n\n` +
        `Foto timbangan kami lampirkan ya Kak. Cucian segera masuk antrean cuci.\nTerima kasih!`
      );
    case 'PROCESSING':
      return (
        `Halo Kak ${booking.customerName},\n\n` +
        `Cucian Kakak (*${booking.bookingCode}*) saat ini sedang diproses (pencucian & pengeringan).\n\n` +
        `Kami pastikan pakaian Kakak dirawat higienis, bersih, dan wangi. Nanti kami kabari lagi jika sudah selesai ya Kak!`
      );
    case 'READY':
      return (
        `Halo Kak ${booking.customerName},\n\n` +
        `Kabar baik! Cucian Kakak (*${booking.bookingCode}*) sudah selesai, wangi, rapi, dan siap ${
          booking.serviceMode === 'PICKUP' ? 'diantar kurir' : 'diambil di outlet'
        }.\n\n` +
        `Status Pembayaran: ${booking.paymentStatus === 'PAID' ? 'LUNAS' : `BELUM LUNAS (${formatRupiah(booking.total)})`}\n\n` +
        `Terima kasih sudah mempercayakan laundry Kakak di ${settings.laundryName}!`
      );
    case 'COMPLETED':
      return (
        `Halo Kak ${booking.customerName},\n\n` +
        `Order laundry *${booking.bookingCode}* telah selesai dan diserahkan.\n\n` +
        `Terima kasih banyak atas kepercayaannya. Ditunggu cucian berikutnya ya Kak!`
      );
  }
}

/**
 * PRD Section 48: Generate wa.me URL
 */
export function createWhatsAppUrl(phone: string, text: string): string {
  const normPhone = normalizePhone(phone);
  const encodedText = encodeURIComponent(text);
  return `https://wa.me/${normPhone}?text=${encodedText}`;
}
